### PR TITLE
Better code-style

### PR DESCRIPTION
**Pull request by jpereira**

### CODE REVIEW

**Comment by jpereira** [comment]
@arr2036 The branch was updated

**Comment by jpereira** [comment]
@arr2036 The branch was updated!

**Comment by arr2036** [comment]
s/cfg/config/
s/conf/config/

**Comment by arr2036** [comment]
consistency is important

**Comment by jpereira** [comment]
@arr2036 The branch was updated!

**Comment by jpereira** [comment]
@arr2036 updated!

**Pull request merged**
