### PR TITLE
Added capabilite to show the version

### PR DESCRIPTION
**Pull request by jpereira**
Very useful to know which the version runs.

It will be displayed during load of Apache
```
[jpereira@jpereira-desktop mod_auth_radius.git]$ tail /var/log/apache2/error.log
.........
[Thu Nov 19 12:03:53.337706 2015] [mpm_prefork:notice] [pid 27383] AH00163: Apache/2.4.12 (Ubuntu) mod_auth_radius/1.6.0 mod_wsgi/4.3.0 Python/2.7.10 configured -- resuming normal operations
.....................
[jpereira@jpereira-desktop mod_auth_radius.git]$ 
```

And, If the apache server runs with option ```ServerTokens Full```, will be displayed in "Server" header.

```
[jpereira@jpereira-desktop mod_auth_radius.git]$ curl -v http://localhost 2>&1 | grep "Server:"
< Server: Apache/2.4.17 mod_auth_radius/1.6.0 mod_wsgi/4.3.0 Python/2.7.10
[jpereira@jpereira-desktop mod_auth_radius.git]$ 
```

### CODE REVIEW

**Comment by arr2036** [comment]
It's not appropriate to call -Werror for anything except debug builds.

**Comment by jpereira** [comment]
@arr2036 updated!

**Comment by jpereira** [comment]
@arr2036 updated!

**Comment by jpereira** [comment]
@arr2036 updated again! :+1:

**Comment by arr2036** [comment]
OK, your use of make is wrong. apxs is not a target, the build production should be the target, and it should depend on the sources... right? That's how make works.

**Comment by jpereira** [comment]
@arr2036 The suggestions is to change the "all:" to call apxs by default. right?

**Comment by arr2036** [comment]
*sigh* i'll fix it

**Comment by arr2036** [comment]
This is what I was talking about https://github.com/FreeRADIUS/mod_auth_radius/commit/6262d6ffb688738de7ef5ae1223872a10b70318e

**Comment by jpereira** [comment]
Very good approach using the ```ifeq ($(which apxs), '')```, :beers:

**Comment by arr2036** [comment]
With your makefile the source would always be rebuilt even if it hadn't changed

**Comment by arr2036** [comment]
that's why I was talking about setting the targets and dependencies

**Comment by jpereira** [comment]
(y)

**Pull request merged**
