### PR TITLE
Added support for build debian packages

### PR DESCRIPTION
**Pull request by jpereira**
Below some evidences.

Building
```
[jpereira@jpereira-desktop mod_auth_radius.git]$ make deb
MOD_RADIUS_VERSION_STRING="1.6.1-git-80c2a88" fakeroot dpkg-buildpackage -b -uc 
dpkg-buildpackage: source package libapache2-mod-auth-radius
dpkg-buildpackage: source version 1.6.1+git
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Jorge Pereira <jpereira@gmail.com>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build mod_auth_radius.git
 debian/rules clean
make[1]: Entering directory '/home/jpereira/Devel/github-jpereira/freeradius/mod_auth_radius.git'
dh_testdir
dh_testroot
/usr/bin/make clean
make[2]: Entering directory '/home/jpereira/Devel/github-jpereira/freeradius/mod_auth_radius.git'
make[2]: Leaving directory '/home/jpereira/Devel/github-jpereira/freeradius/mod_auth_radius.git'
dh_clean build-stamp .libs/mod_auth_radius.so
make[1]: Leaving directory '/home/jpereira/Devel/github-jpereira/freeradius/mod_auth_radius.git'
 debian/rules build
make[1]: Entering directory '/home/jpereira/Devel/github-jpereira/freeradius/mod_auth_radius.git'
dh_testdir
apxs -DMOD_RADIUS_AUTH_VERSION_STRING='\"1.6.1-git-80c2a88\"' \
		-Wall -c mod_auth_radius.c
/usr/share/apr-1.0/build/libtool --silent --mode=compile --tag=disable-static x86_64-linux-gnu-gcc -std=gnu99 -prefer-pic -pipe -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -D_FORTIFY_SOURCE=2   -DLINUX -D_REENTRANT -D_GNU_SOURCE  -pthread  -I/usr/include/apache2  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0 -I/usr/include -DMOD_RADIUS_AUTH_VERSION_STRING=\"1.6.1-git-80c2a88\"  -c -o mod_auth_radius.lo mod_auth_radius.c && touch mod_auth_radius.slo
/usr/share/apr-1.0/build/libtool --silent --mode=link --tag=disable-static x86_64-linux-gnu-gcc -std=gnu99 -Wl,--as-needed -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now    -o mod_auth_radius.la  -rpath /usr/lib/apache2/modules -module -avoid-version    mod_auth_radius.lo
make[1]: Leaving directory '/home/jpereira/Devel/github-jpereira/freeradius/mod_auth_radius.git'
 debian/rules binary
make[1]: Entering directory '/home/jpereira/Devel/github-jpereira/freeradius/mod_auth_radius.git'
#nothing to do
dh_testdir
apxs -DMOD_RADIUS_AUTH_VERSION_STRING='\"1.6.1-git-80c2a88\"' \
		-Wall -c mod_auth_radius.c
/usr/share/apr-1.0/build/libtool --silent --mode=compile --tag=disable-static x86_64-linux-gnu-gcc -std=gnu99 -prefer-pic -pipe -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -D_FORTIFY_SOURCE=2   -DLINUX -D_REENTRANT -D_GNU_SOURCE  -pthread  -I/usr/include/apache2  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0 -I/usr/include -DMOD_RADIUS_AUTH_VERSION_STRING=\"1.6.1-git-80c2a88\"  -c -o mod_auth_radius.lo mod_auth_radius.c && touch mod_auth_radius.slo
/usr/share/apr-1.0/build/libtool --silent --mode=link --tag=disable-static x86_64-linux-gnu-gcc -std=gnu99 -Wl,--as-needed -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now    -o mod_auth_radius.la  -rpath /usr/lib/apache2/modules -module -avoid-version    mod_auth_radius.lo
dh_testdir
dh_testroot
dh_prep
dh_installdirs
dh_apache2 
dh_testdir
dh_testroot
dh_installchangelogs ChangeLog
dh_installdocs README.asciidoc
dh_installexamples htaccess httpd.conf
dh_strip
dh_compress 
dh_fixperms
dh_installdeb
dh_shlibdeps
dh_gencontrol
dh_md5sums
dh_builddeb
dpkg-deb: building package 'libapache2-mod-auth-radius' in '../libapache2-mod-auth-radius_1.6.1+git_amd64.deb'.
make[1]: Leaving directory '/home/jpereira/Devel/github-jpereira/freeradius/mod_auth_radius.git'
 dpkg-genchanges -b >../libapache2-mod-auth-radius_1.6.1+git_amd64.changes
dpkg-genchanges: binary-only upload (no source code included)
 dpkg-source --after-build mod_auth_radius.git
dpkg-buildpackage: binary-only upload (no source included)
[jpereira@jpereira-desktop mod_auth_radius.git]$
```

Packages
```
[jpereira@jpereira-desktop mod_auth_radius.git]$ ls -l ../libapache2-mod-auth-radius_1.6.1+git_amd64.*
-rw-rw-r-- 1 jpereira jpereira   838 Nov 19 16:37 ../libapache2-mod-auth-radius_1.6.1+git_amd64.changes
-rw-r--r-- 1 jpereira jpereira 16486 Nov 19 16:37 ../libapache2-mod-auth-radius_1.6.1+git_amd64.deb
[jpereira@jpereira-desktop mod_auth_radius.git]$
```

Installation
```
[jpereira@jpereira-desktop mod_auth_radius.git]$ sudo dpkg -i ../libapache2-mod-auth-radius_1.6.1+git_amd64.deb 
(Reading database ... 381482 files and directories currently installed.)
Preparing to unpack .../libapache2-mod-auth-radius_1.6.1+git_amd64.deb ...
Unpacking libapache2-mod-auth-radius (1.6.1+git) over (1.6.1+git) ...
Setting up libapache2-mod-auth-radius (1.6.1+git) ...
apache2_invoke auth_radius: already enabled
[jpereira@jpereira-desktop mod_auth_radius.git]$
```

Package informations
```
[jpereira@jpereira-desktop mod_auth_radius.git]$ dpkg -s libapache2-mod-auth-radius
Package: libapache2-mod-auth-radius
Status: install ok installed
Priority: optional
Section: web
Installed-Size: 59
Maintainer: Jorge Pereira <jpereiran@gmail.com>
Architecture: amd64
Version: 1.6.1+git
Depends: libc6 (>= 2.15), apache2-api-20120211
Suggests: freeradius-server, freeradius-utils, apache2
Conffiles:
 /etc/apache2/mods-available/auth_radius.load b3f945eae85dd0b407a686338ff1ce47
Description: Apache 2.x module for RADIUS authentication
 mod_auth_radius is an Apache 2.x module for authenticating users
 against information stored in a RADIUS server.
Homepage: http://www.freeradius.org/
[jpereira@jpereira-desktop mod_auth_radius.git]$
```

Restart the service
```
[jpereira@jpereira-desktop mod_auth_radius.git]$ sudo /etc/init.d/apache2 restart
[ ok ] Restarting apache2 (via systemctl): apache2.service.
[jpereira@jpereira-desktop mod_auth_radius.git]$
```

Sample of output
```
[jpereira@jpereira-desktop mod_auth_radius.git]$ curl -v http://localhost/ 2>&1 | grep Server:
< Server: Apache/2.4.12 (Ubuntu) mod_auth_radius/1.6.1-git-80c2a88 mod_wsgi/4.3.0 Python/2.7.10
[jpereira@jpereira-desktop mod_auth_radius.git]$ 
```

### CODE REVIEW

**Comment by arr2036** [comment]
There are already debian src packages available?

**Comment by jpereira** [comment]
like the debian spirit... OLD! abandoned

**Comment by arr2036** [comment]
I found ones for 1.5.8...

**Comment by jpereira** [comment]
As the same situation of freeradius-server that is available in 

```
[jpereira@jpereira-desktop mod_auth_radius.git]$ apt-cache show freeradius | grep Version
Version: 2.1.12+dfsg-1.3ubuntu5
[jpereira@jpereira-desktop mod_auth_radius.git]$ 
```

**Comment by jpereira** [comment]
I think that we should keep this in original project. Much better to update the packages.

**Comment by arr2036** [comment]
1.5.8 was the previous latest version until I started 1.6 yesterday

**Comment by arr2036** [comment]
I think we should work with the debian people, so the packages actually get into debian and people can install them.

**Comment by arr2036** [comment]
So if you want to create updated versions of the debian packaging and submit it back to debian that would be helpful.

**Comment by arr2036** [comment]
The only reason we maintain packages for freeradius, is because the debian maintainers are so far behind, and we also want to be agents of change in the debian ecosystem.  We want to define the package structure so that it's sane.  Here there's a single source file, I don't see there's an advantage to maintaining a fork of the debian packaging.

**Comment by arr2036** [comment]
@alandekok opinions?

**Comment by arr2036** [comment]
and please *STOP* putting unrelated changes in the same pull request

**Comment by jpereira** [comment]
In my point of view. I think that we need to keep this in the original code to motivate the evolution of module. It's more useful to checkout the project and build the latest package.

**Pull request closed without merging**
